server:
  port: ${PORT:8080}

spring:
  application:
    name: ms-order

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: ms-order-group
      auto-offset-reset: latest

  data:
    mongodb:
      database: ${MONGO_DATABASE:admin}
      uri: ${MONGO_URI:mongodb://root:root@localhost:27017/}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER:localhost}:8761/eureka
  instance:
    instance-id: ${PORT:8080}

logging:
  level:
    org:
      apache:
        kafka: OFF