server:
  port: ${PORT:8081}

spring:
  application:
    name: ms-inventory

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: ms-inventory-group
      auto-offset-reset: latest
    topic:
      inventory-validation: inventory-validation
      inventory-rollback: inventory-rollback
      register-inventory: register-inventory
      update-inventory: update-inventory

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${DATABASE_NAME:inventory-db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  flyway:
    baseline-on-migrate: true
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER:localhost}:8761/eureka
  instance:
    instance-id: ${PORT:8081}

logging:
  level:
    org:
      apache:
        kafka: OFF
