server:
  port: ${PORT:8080}

spring:
  application:
    name: ms-authentication

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6739}
      password: ${REDIS_PASSWORD:root}

  cache:
    type: redis
    cache-names: already_authenticated_users

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER:localhost}:8761/eureka
  instance:
    instance-id: ${PORT:8080}

logging:
  level:
    org:
      apache:
        kafka: OFF