server:
  port: ${PORT:8085}

spring:
  application:
    name: ms-accounts

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: ms-accounts-group
      auto-offset-reset: latest
    topic:
      account-address-validation: account-address-validation
      account-address-rollback: account-address-rollback

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5434}/${DATABASE_NAME:account-db}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  flyway:
    baseline-on-migrate: true
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER:localhost}:8761/eureka
  instance:
    instance-id: ${PORT:8085}

logging:
  level:
    org:
      apache:
        kafka: OFF
