server:
  port: ${PORT:8082}

spring:
  application:
    name: ms-product

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: ms-product-group
      auto-offset-reset: latest
    topic:
      product-validation: product-validation
      product-rollback: product-rollback
      link-inventory: link-inventory
      update-product-status: update-product-status

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:root}


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${DATABASE_NAME:product-db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  cache:
    type: redis
    cache-names: searched_products
    redis:
      time-to-live: 60000

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER:localhost}:8761/eureka
  instance:
    instance-id: ${PORT:8082}


logging:
  level:
    org:
      apache:
        kafka: OFF
